"""empty message

Revision ID: 3c4a15dc8dd5
Revises: 4b4e5e8d6e4a
Create Date: 2016-08-15 08:22:42.929772

"""

# revision identifiers, used by Alembic.
revision = '3c4a15dc8dd5'
down_revision = '4b4e5e8d6e4a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('zhifubao', sa.String(length=64), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'zhifubao')
    ### end Alembic commands ###
