"""empty message

Revision ID: 4b4e5e8d6e4a
Revises: 51f5ccfba190
Create Date: 2016-08-14 16:57:56.635481

"""

# revision identifiers, used by Alembic.
revision = '4b4e5e8d6e4a'
down_revision = '51f5ccfba190'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('accountname', sa.String(length=64), nullable=True))
    op.add_column('users', sa.Column('accountpassword_hash', sa.String(length=128), nullable=True))
    op.create_index('ix_users_accountname', 'users', ['accountname'], unique=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_accountname', 'users')
    op.drop_column('users', 'accountpassword_hash')
    op.drop_column('users', 'accountname')
    ### end Alembic commands ###
